data:
    feature: data256/dev/feature.csv
    label: data256/dev/label.csv
    class_indice_file: data256/metadata/class_label_indices.txt
    stratified: True

dataloader_args:
    batch_size: 64
    num_workers: 16

optimizer:
    type: AdamW
    args:
        lr: 0.0005

epochs: 50 
model:
    type: Crnn
    args: {}

outputpath: experiments256/
