data:
  class_indice_file: data256/metadata/class_label_indices.txt
  feature: data256/dev/feature.csv
  label: data256/dev/label.csv
  stratified: true
dataloader_args:
  batch_size: 64
  num_workers: 16
early_stop: 7
epochs: 50
loss: BceLoss
model:
  args: {}
  type: Crnn
num_workers: 16
optimizer:
  args:
    lr: 0.0005
  type: AdamW
outputpath: experiments256/
scheduler_args:
  factor: 0.1
  patience: 3
